[build]
  builder = "image"
  image = "devlikeapro/waha"

[deploy]
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
  path = "/api/server/status"
  intervalSeconds = 30
  timeoutSeconds = 10
